### ISSUE TITLE
The Anderson NT was a paragraphed translation

### ISSUE THREAD

**Issue by DavidHaslam** [BeTheLight/ENG-B1-Anderson1864-pd-USFM#5]
I have a copy of the **University of Michigan** facsimile reprint of the **Anderson NT**.

It's clearly a paragraphed translation.

Currently the USFM files have a **\p** marker before every verse. 
Most of these should be removed, leaving a paragraph tag only before each original paragraph.

You can see the original paragraph layout in the PDF download from the Internet Archive.

**Comment by cmahte** [comment]
If I had a list for each paragraph in the Anderson NT, it would be fairly simple to transform that into a paragraph text. Building such a list for the 1911 Bible has taken about 4 hours, but needs validation prior to implementation. 

To do: 
Option A: create a new paragraphed USFM 
Option B: Create a list of each paragraph in the 1864 printing (or facsimilies of it) that show the paragraphs in one of the forms that follow. I can process that list into the USFM using specialized text tools. 

My working list of AV1911 paragraphs looks like 

MAT- Matthew
	1.1
	2.1
	2.9
	2.13
	2.16
	2.19
	3.1
	3.7
	3.13
	3.16
	4.1
...

In retrospect, It should have looked like what follows,  because I'm transforming the list above to this, and the latter would have saved me ~60% of the keystrokes to create the file. That is the first step is to chop out about 50% of my typing.  

\id MAT
\c 1
1
\c 2
1
9
13
16
19
\c 3
1
7
13
16
\c 4
1 (etc.)  
\id MRK (the next book continues in the same text file.)
\c1 
...

**Comment by DavidHaslam** [comment]
I have forked the repo and already made a good start on fixing textual errors and SFM tags.

My **Way of Working** is to go through the SFM files in **size order** starting with the _smallest_.

**Comment by cmahte** [comment]
Hooray!

If the final version of your work ends up residing only on the crosswire
git, please loop me into that repo at some point. :-) I do hope to keep
this place up to date. :-)

...

Originally, I had begun work to include the Jewish School and Family Bible
as a companion OT module to this NT module.  It's contemporary in time to
the Anderson NT, but otherwise has no relation. It was created in London in
the 1855-1864 time frame, and predates the earliest "Jewish roots" Bible by
a few years. I'd be happy to resurrect that work as well, if I can locate
it on my collection of old hard drives.

https://archive.org/search.php?query=creator%3A%22Benisch%2C+A.+%28Abraham%29%2C+1811-1878%22

**Comment by DavidHaslam** [comment]
I’d have to take cross platform action to do that. 

For my part, it’s just as fine to stick to using GitHub for this project. 

It’s not as if I don’t have any other repos here. 

Typing this on my iPhone SE using the CodeHub app.

**Comment by DavidHaslam** [comment]
My procedure for each SFM file is currently as follows:

1. Remove all `\p` in one fell swoop. 
2. Remove `CHAPTER ` from the `\cl ` tags
3. Replace \x27 by \x{2019} as the typographical apostrophe. 
4. Insert `\p` for each paragraph start. Almost always need one at the start of a chapter. 
5. Insert `\add ...\add*` where the verse text is in italics. 
6. Insert `horizontal bar` (aka quotation dash) where seen in the PDF. 
7. Study the location of each word-wrap hyphen in the PDF and fix the text where necessary. 
8. Insert any headings found in the PDF. Romans was special in this respect. 
9. Correct any spelling errors such as `Gains` to `Gaius` or `Phoebe` to `Phœbe` or `Sostlienes` to `Sosthenes`, etc. 
10. Anything else.....

By recording my methodology here it may shed light for other projects.

**Comment by DavidHaslam** [comment]
Merged pull request #9
