### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by DavidHaslam** [BeTheLight/ENG-B1-Anderson1864-pd-USFM#6]
Suggest move the USFM files into a folder called **usfm**.

This would be a less cluttered appearance to visitors.

Also suggest add a **README.md** file at top level.

**Comment by cmahte** [comment]
What you are suggesting is appropriate, but has implications for my personal archive, from which this started. Please set up the file structure you envision for the Anderson project first, then let me work out how this affects my file local structure before applying across the board. I have a large number of works locally.. and I locally archive more than I publish.  

I am adding you as an 'owner' to the Bethelight organization. You should be 'admin' but I don't see that level, and I'm lazy to research this.(*) Becoming Admin may change your views.... just mentioning to reduce confusion. If/when I do find admin instead of 'owner' I will adjust that. The only real difference is that as owner you can delete everything at one time.

* -  (school starts again in ~10 days, and I'm not on track to complete my summertime goal of publishing the 1911 Bible...) 

Also, The name of the organization is spurious. BeTheLight is an idea that is supposed to be about discipleship in all languages; not about a library of all English Scripture works. The spec'd B in the naming runs from A-S, and originally was supposed to only include 1 translation per language. I'm open to moving the scripture USFM to a more appropriate Organizational location. 

A- Literacy
B- Scriptures (Bibles)
C- Christianity (What?) works
D- Discipleship (Seeking, Growing, Following... ) works
E- Evangelism (you should come too) works
F- Friends (Works better together) works
G- Growth (How to use A-F to make community) works
H - Help (in times of need: Death, Marriage, etc.) 
etc.

**Comment by DavidHaslam** [comment]
Ownership is a responsibility I did not ask for - nor did I wish to have.
It would have been better to have asked for my assent before making this change unilaterally.

The Anderson NT project is not on my priorities list. 
The few issues I added already were merely humble attempts to make helpful observations.

**Comment by cmahte** [comment]
David,

No worries, I'll remove you. :-)  I'm eager for help. I understand it's not
your priority. I do appreciate your help and suggestons. I'll moderate my
enthusiasm in future.

**Comment by cmahte** [comment]
And by remove, I meant I have returned you to "member" status.

**Comment by DavidHaslam** [comment]
Thanks.

**Comment by DavidHaslam** [comment]
If you have an iPhone or iPad, suggest install the CodeHub app. 

Using this right now to comment.

**Comment by cmahte** [comment]
I had a palm phone in 2002 that was connected to the web. After 3 years of
being the only one in the room who was immersed in the mobile web, I
realized I had been assimilated, and lost much of my life to technology. I
"unplugged" to a phone that wasn't always connected. :-) As a result, I'm a
little less attentive while a the computer, but I am much more alive when
away from the computer. :-)

These day's I feel like Ralph (Emerson). I'm pretty much always the only
one in the room not connected without an off switch, and people are
starting to notice. and make suggestions. :-)

Don't get me wrong, I use technology. However, I don't allow it
unrestrained access me any time of the day or night. Technology is
available to me, not the vice-versa. Even my cell phone actually goes into
dark mode for voice calls. put your note in my queue and I'll respond when
I'm available. :-)

**Comment by DavidHaslam** [comment]
I have recently forked the repository and am in the process of making significant changes in my Editing branch.

NB. I have **not** _renamed_ the SFM files, but I have _moved_ them to a **USFM** directory.

**Comment by DavidHaslam** [comment]
Merged pull request #9
